### PR TITLE
works with non local file storages

### PR DESCRIPTION
**Pull request by vitaly4uk**
Some file storage not implement path property. In that case now it will use url for guessing mimetype of uploaded file.

### CODE REVIEW

**Comment by carljm** [comment]
Looks good; any chance you could provide a test?

**Comment by vitaly4uk** [comment]
What do you mean by provide a test? Some unittest? I'm using that code in few real projects. Haven't any issue yet.

**Comment by carljm** [comment]
Yes, I meant a unit test integrated with the existing test suite.

**Comment by vitaly4uk** [comment]
Sorry, I couldn't implement any unit tests for my changes. It relay on filestorage that doesn't exist in you project. Should I create fake filestorage just to test three rows of code? My changes really trivial, just use another property if first one not implemented in file object.

**Pull request merged**
